[package]
name = "life"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[rust]
debuginfo-level = 1
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rayon = "*"
crossterm = "*"
sdl2 = "*"